### ISSUE TITLE
kern tone marks closer to overhanging vowels

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-nokyung#17]
Where a vowel has an overhang (or underhang) as in U+19B4 and perhaps U+19BE it would be good to kern the following tone mark closer to the main stem:

![img_20160509_151515](https://cloud.githubusercontent.com/assets/5687149/15133345/129e6136-168c-11e6-8757-f8da82d55f69.jpeg)

**Comment by ericjding** [comment]
I hope your team can take a look at adding kerning to Nokyung soon.  We're on the verge of formally publishing the first Dai children's board book that I know of, using Nokyung font, and I've manually kerned some of the text to improve its appearance. This is feasible for a very short story book, but not for some of the longer projects we have coming up soon in the pipeline. Thanks!

**Comment by devosb** [comment]
Kerning added in https://github.com/silnrsi/font-nokyung/commit/b33cde186169143892b1044e68cac67ed900b536
