### ISSUE TITLE
Complete bold face design

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-nokyung#5]

**Comment by ericjding** [comment]
@jvgaultney Has there been any further planning on when this bold face design might be completed? The language team using this font most extensively is nearing the stage where they'd like to print some completed books, but they'd prefer to wait until the bold face is completed if it's within reach. Thanks.

**Comment by jvgaultney** [comment]
It's been dormant while we've worked on other higher-priority projects. What would wake it up would be a specific need - which you've just mentioned. We won't be able to give it immediate attention, but we'll place it back in the active list as soon as we can.

**Comment by sdysart** [comment]
@jvgaultney  We are looking to put up a webonary page for a lexicon that makes use of the Nokyung font and are running into the problem of the incomplete bold face design.  Please let us know when the bold design is completed, so that we can use it in our webonary page.

**Comment by jvgaultney** [comment]
Yes I know - I've already been corresponding with a few others working on the Webonary dictionary.   We're working on it, but have very limited staff at the moment. The best way to receive news about our font releases is to join the SIL Font News announcement list. Details at http://scripts.sil.org/SILFontNews

**Comment by jvgaultney** [comment]
Addressed in release 1.490. https://github.com/silnrsi/font-nokyung/releases/tag/v1.490
